# -*- coding: utf-8 -*-
"""Customer Churn Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_QjlFC39XnqIhQzCH7nW_tmsglF4BWd
"""

import pandas as pd

# Read the CSV file
df = pd.read_csv("Customer Churn Analysis.csv")

# Display the first few rows of the DataFrame
print(df.head(10))

print("Missing values in each column:")
print(df.isnull().sum())

print("Data Types of the fileds having ",df.dtypes)

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print(df.dtypes)

missing_values = df.isnull().sum()
print("\nMissing Values Before Cleaning:")
print(missing_values)

df.dropna(inplace=True)

df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

print("\nCleaned Dataset:")
print(df.head())

print("\nData Types After Cleaning:")
print(df.dtypes)

# Display the number of churned vs. retained customers
print("\nChurned vs Retained Customers:")
print(df['Churn'].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

# 1. Churn Distribution (Pie Chart)
plt.figure(figsize=(6, 6))
churn_counts = df['Churn'].value_counts()
plt.pie(churn_counts, labels=['Retained', 'Churned'], autopct='%1.1f%%', startangle=90, colors=['lightgreen', 'lightcoral'])
plt.title('Churn Distribution')
plt.show()
# 2. Gender vs. Churn (Bar Chart)
plt.figure(figsize=(8, 6))
sns.countplot(x='gender', hue='Churn', data=df, palette='Set2')
plt.title('Gender vs. Churn')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

# 3. SeniorCitizen vs. Churn (Bar Chart)
plt.figure(figsize=(8, 6))
sns.countplot(x='SeniorCitizen', hue='Churn', data=df, palette='Set1')
plt.title('Senior Citizen vs. Churn')
plt.xlabel('Senior Citizen (0 = No, 1 = Yes)')
plt.ylabel('Count')
plt.show()

# 4. Contract Type vs. Churn (Bar Chart)
plt.figure(figsize=(8, 6))
sns.countplot(x='Contract', hue='Churn', data=df, palette='Set3')
plt.title('Contract Type vs. Churn')
plt.xlabel('Contract Type')
plt.ylabel('Count')
plt.show()

# 5. Monthly Charges vs. Churn (Boxplot)
plt.figure(figsize=(8, 6))
sns.boxplot(x='Churn', y='MonthlyCharges', data=df, palette='coolwarm')
plt.title('Monthly Charges vs. Churn')
plt.xlabel('Churn')
plt.ylabel('Monthly Charges')
plt.show()

# 6. Total Charges vs. Churn (Boxplot)
plt.figure(figsize=(8, 6))
sns.boxplot(x='Churn', y='TotalCharges', data=df, palette='coolwarm')
plt.title('Total Charges vs. Churn')
plt.xlabel('Churn')
plt.ylabel('Total Charges')
plt.show()

# 7. Internet Service vs. Churn (Bar Chart)
plt.figure(figsize=(8, 6))
sns.countplot(x='InternetService', hue='Churn', data=df, palette='Set2')
plt.title('Internet Service vs. Churn')
plt.xlabel('Internet Service')
plt.ylabel('Count')
plt.show()